const services = [
  {
    id: 'laundry',
    title: 'Laundry',
    description: 'Quick and affordable local laundry services.',
    distance: '1.2 km',
    coords: [8.233, 124.247],
    category: 'Home',
    rating: 4.8,
    image: 'https://i.pinimg.com/originals/55/ea/a0/55eaa00ac768ebd7672a11499e620a04.jpg',
    showInAll: true,
  },
  {
    id: 'printing',
    title: 'Printing',
    description: 'Fast document printing and copying nearby.',
    distance: '800 m',
    coords: [8.226, 124.244],
    category: 'Office',
    rating: 4.3,
    image: 'https://tse4.mm.bing.net/th/id/OIP.Vq2T4aL0BpgEgtYutG-GcAHaEO?pid=Api&P=0&h=180',
    showInAll: true,
  },
  {
    id: 'boarding-house',
    title: 'Boarding House',
    description: 'Affordable boarding options close by.',
    distance: '2.1 km',
    coords: [8.221, 124.249],
    category: 'Boarding House',
    rating: 4.5,
    image: 'https://tse2.mm.bing.net/th/id/OIP.xTr8dGzW2blLTkXQSrRadgHaE8?pid=Api&P=0&h=180',
    showInAll: true,
  },
  {
    id: 'penny-boarding-house',
    title: 'Penny Boarding House',
    description: 'Convenient boarding house for nearby residents and students.',
    distance: 'Nearby',
    coords: [8.228, 124.245],
    category: 'Boarding House',
    rating: 4.7,
    image: '/images/penny.png',
    fullAddress: '123 Riverside St, Iligan City',
    lat: 8.228,
    long: 124.245,
    openTime: '08:00',
    closeTime: '20:00',
    availability: 'Open',
    residentType: 'Students',
    roomTypes: ['Single', 'Shared'],
    roomCount: 30,
    availableRooms: 5,
    monthlyRent: '₱3,000',
    amenities: ['WiFi', 'Fan', 'Shared Kitchen'],
    rules: ['No smoking', 'Quiet hours after 10 PM'],
    contactNumber: '0917-123-4567',
  },
  {
    id: 'sunny-dorm',
    title: 'Sunny Dorm',
    description: 'Bright and budget-friendly dormitory with easy access to town.',
    distance: '1.6 km',
    coords: [8.227, 124.247],
    category: 'Boarding House',
    rating: 4.6,
    image: '/images/sunny.png',
    fullAddress: '45 Sunflower Ave, Iligan City',
    lat: 8.227,
    long: 124.247,
    openTime: '08:00',
    closeTime: '20:00',
    availability: 'Open',
    residentType: 'Mixed',
    roomTypes: ['Single', 'Double', 'Shared'],
    roomCount: 20,
    availableRooms: 6,
    monthlyRent: '₱3,500',
    amenities: ['WiFi', 'Air Conditioning', 'Study Area'],
    rules: ['No smoking', 'Quiet hours after 10 PM'],
    contactNumber: '0917-234-5678',
  },
  {
    id: 'riverside-lodge',
    title: 'Riverside Lodge',
    description: 'Quiet lodge near the river with comfortable rooms.',
    distance: '2.4 km',
    coords: [8.225, 124.244],
    category: 'Boarding House',
    rating: 4.8,
    image: '/images/riverside.png',
    fullAddress: '78 Riverbank Rd, Iligan City',
    lat: 8.225,
    long: 124.244,
    openTime: '08:00',
    closeTime: '20:00',
    availability: 'Open',
    residentType: 'Mixed',
    roomTypes: ['Single', 'Double'],
    roomCount: 18,
    availableRooms: 3,
    monthlyRent: '₱4,000',
    amenities: ['WiFi', 'Hot Water', 'Laundry Area'],
    rules: ['No smoking', 'Quiet hours after 10 PM'],
    contactNumber: '0917-345-6789',
  },
  {
    id: 'amirah-dormitory',
    title: 'AMERAH Dormitory',
    description: 'Clean dormitory rooms with a convenient central location.',
    distance: '2.0 km',
    coords: [8.224, 124.246],
    category: 'Boarding House',
    rating: 4.5,
    image: '/images/amerah.png',
    fullAddress: '12 Central Plaza, Iligan City',
    lat: 8.224,
    long: 124.246,
    openTime: '08:00',
    closeTime: '20:00',
    availability: 'Open',
    residentType: 'Female',
    roomTypes: ['Single', 'Shared'],
    roomCount: 22,
    availableRooms: 4,
    monthlyRent: '₱3,200',
    amenities: ['WiFi', 'Security', 'Common Kitchen'],
    rules: ['No smoking', 'Quiet hours after 10 PM'],
    contactNumber: '0917-456-7890',
  },
  {
    id: 'jr-boys-boarding-house',
    title: 'JR Boys Boarding House',
    description: 'Practical boarding house for students and workers.',
    distance: '2.3 km',
    coords: [8.226, 124.243],
    category: 'Boarding House',
    rating: 4.1,
    image: '/images/jr.png',
    fullAddress: '5 Northgate St, Iligan City',
    lat: 8.226,
    long: 124.243,
    openTime: '08:00',
    closeTime: '20:00',
    availability: 'Open',
    residentType: 'Male',
    roomTypes: ['Single', 'Shared'],
    roomCount: 25,
    availableRooms: 7,
    monthlyRent: '₱3,500',
    amenities: ['WiFi', 'Fan', 'Study Area'],
    rules: ['No smoking', 'Quiet hours after 10 PM'],
    contactNumber: '0917-123-4567',
  },
  {
    id: 'food-delivery',
    title: 'Food Delivery',
    description: 'Fast food delivery from local restaurants.',
    distance: '1.5 km',
    coords: [8.234, 124.248],
    category: 'Food',
    rating: 4.2,
    image: 'https://cdn.pixabay.com/photo/2015/04/08/13/13/food-712665_1280.jpg',
    showInAll: true,
  },
  {
    id: 'pharmacy',
    title: 'Pharmacy',
    description: 'Nearby pharmacy for medicines and healthcare items.',
    distance: '650 m',
    coords: [8.229, 124.248],
    category: 'Health',
    rating: 4.4,
    image: 'https://tse3.mm.bing.net/th/id/OIP.rbj_nHwRqTsmkzWWOqU3bgHaE7?pid=Api&P=0&h=180',
    showInAll: true,
  },
  {
    id: 'grocery',
    title: 'Grocery',
    description: 'Local grocery store with fresh produce.',
    distance: '900 m',
    coords: [8.227, 124.246],
    category: 'Shopping',
    rating: 4.0,
    image: 'https://tse4.mm.bing.net/th/id/OIP.B6YlCtNyvXJW_OvbD5osHwHaFj?pid=Api&P=0&h=180',
    showInAll: true,
  },
  {
    id: 'repair-services',
    title: 'Repair Services',
    description: 'Tool and gadget repair specialists nearby.',
    distance: '1.9 km',
    coords: [8.230, 124.243],
    category: 'Repair',
    rating: 4.6,
    image: 'https://tse3.mm.bing.net/th/id/OIP.1LgriQpbIsdw5Pg6BYI8ygHaEK?pid=Api&P=0&h=180',
    showInAll: true,
  },
  {
    id: 'internet-cafe',
    title: 'Internet Café',
    description: 'Workspace and online access at affordable rates.',
    distance: '750 m',
    coords: [8.228, 124.242],
    category: 'Internet',
    rating: 4.1,
    image: 'https://tse2.mm.bing.net/th/id/OIP.xZNClaC1JNGUxH6P-FgcFAHaEK?pid=Api&P=0&h=180',
    showInAll: true,
  },
  // --- Laundry entries ---
  {
    id: 'spinnr-launderette',
    title: 'SPINNR Launderette',
    description: 'Local launderette with self-service and drop-off options.',
    distance: '1.1 km',
    coords: [8.2295, 124.2445],
    category: 'Home',
    rating: 4.0,
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 'rhyme-enterprises-laundry',
    title: 'Rhyme Enterprises Laundry Shop',
    description: 'Reliable laundry services with quick turnaround.',
    distance: '900 m',
    coords: [8.2278, 124.2462],
    category: 'Home',
    rating: 3.9,
    image: '/images/rhyme.png',
  },
  {
    id: 'lavatronic',
    title: 'Lavatronic',
    description: 'Coin-operated laundry with large-capacity machines.',
    distance: '1.4 km',
    coords: [8.231, 124.246],
    category: 'Home',
    rating: 4.1,
    image: '/images/lavatronic.png',
  },
  {
    id: 'lg-laundry-lounge',
    title: 'LG Laundry Lounge by Skilcraft',
    description: 'Commercial laundry supplier and services.',
    distance: '2.0 km',
    coords: [8.225, 124.248],
    category: 'Home',
    rating: 3.7,
    image: '/images/lg.png',
  },
  {
    id: 'splash-coinopt-laundry',
    title: 'Splash coin-opt Laundry',
    description: 'Small coin laundry for quick loads.',
    distance: '1.8 km',
    coords: [8.224, 124.242],
    category: 'Home',
    rating: 3.5,
    image: '/images/splash.png',
  },

  // --- Printing entries ---
  {
    id: 'anies-sticker-printing',
    title: 'Anies Sticker Printing Services',
    description: 'Sticker and label printing for businesses and events.',
    distance: '850 m',
    coords: [8.2265, 124.2435],
    category: 'Office',
    rating: 4.2,
    image: '/images/annies.png',
  },
  {
    id: 'xeew-printing',
    title: 'XEEV Printing Services',
    description: 'Digital printing and promotional materials.',
    distance: '1.0 km',
    coords: [8.2288, 124.2448],
    category: 'Office',
    rating: 4.0,
    image: '/images/xeev.png',
  },
  {
    id: 'ikka-crafts',
    title: 'Ikka Crafts',
    description: 'Small-format printing and crafts shop.',
    distance: '700 m',
    coords: [8.2255, 124.2455],
    category: 'Office',
    rating: 3.8,
    image: '/images/ikka.png',
  },
  {
    id: 'emrys-industries',
    title: 'Emrys Industries',
    description: 'Commercial print and signage maker.',
    distance: '2.2 km',
    coords: [8.223, 124.247],
    category: 'Office',
    rating: 4.1,
    image: '/images/emrys.png',
  },

  // --- Food Delivery / Restaurants ---
  {
    id: 'kfc-iligan',
    title: 'KFC Iligan',
    description: 'Fast food - popular chicken franchise with delivery.',
    distance: '1.3 km',
    coords: [8.230, 124.246],
    category: 'Food',
    rating: 3.9,
    image: '/images/kfc.png',
  },
  {
    id: 'arabigo-coffee-roastery',
    title: 'Arabigo Coffee Roastery',
    description: 'Local coffee roastery and café with delivery partners.',
    distance: '900 m',
    coords: [8.229, 124.247],
    category: 'Food',
    rating: 4.8,
    image: '/images/arabigo.png',
  },
  {
    id: 'biano-pizza-tibanga',
    title: "Biaño's Pizza Iligan - Tibanga",
    description: 'Popular pizza place offering delivery and takeout.',
    distance: '1.6 km',
    coords: [8.227, 124.249],
    category: 'Food',
    rating: 4.6,
    image: '/images/bianos.png',
  },
  {
    id: 'lamy-food-hauz',
    title: 'LAMy Food Hauz',
    description: 'Local favorite food delivery and menu specials.',
    distance: '1.9 km',
    coords: [8.2245, 124.2445],
    category: 'Food',
    rating: 4.0,
    image: '/images/lamy.png',
  },
  {
    id: 'jollibee-iligan-tibanga',
    title: 'Jollibee Iligan Tibanga DT',
    description: 'Fast food chain location offering delivery.',
    distance: '1.2 km',
    coords: [8.2282, 124.2439],
    category: 'Food',
    rating: 4.1,
    image: '/images/jollibee.png',
  },
  {
    id: 'albertos-pizza',
    title: "Alberto's Pizza",
    description: 'Local pizza joint with delivery options.',
    distance: '1.7 km',
    coords: [8.2269, 124.2451],
    category: 'Food',
    rating: 4.2,
    image: '/images/albertos-pizza.png',
  },
  {
    id: 'dads-grub',
    title: "Dad's Grub",
    description: 'Comfort food and delivery-friendly menu.',
    distance: '1.5 km',
    coords: [8.2273, 124.2468],
    category: 'Food',
    rating: 4.0,
    image: '/images/dad.png',
  },
  {
    id: 'clouds-cafe',
    title: 'Clouds Café',
    description: 'Cozy café offering light meals and delivery.',
    distance: '1.0 km',
    coords: [8.2285, 124.2465],
    category: 'Food',
    rating: 4.3,
    image: '/images/clouds.png',
  },
  {
    id: 'urban-roastery-kitchen',
    title: 'URBAN Roastery + Kitchen',
    description: 'Roastery with breakfast and delivery menu.',
    distance: '1.4 km',
    coords: [8.2292, 124.2442],
    category: 'Food',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=60',
  },

  // --- Pharmacy entries ---
  {
    id: 'eagles-pharmahealth',
    title: 'Eagles Pharmahealth MULTI-SPECIALTY',
    description: 'Pharmacy and diagnostic supplies.',
    distance: '1.6 km',
    coords: [8.2312, 124.2475],
    category: 'Health',
    rating: 4.9,
    image: '/images/eagles.png',
  },
  {
    id: '18th-avenue-pharmacy',
    title: '18th Avenue Pharmacy',
    description: 'Pharmacy servicing the 18th Avenue area.',
    distance: '1.8 km',
    coords: [8.2248, 124.2481],
    category: 'Health',
    rating: 4.1,
    image: '/images/18th-pharmacy.png',
  },
  {
    id: 'unilab-pharmacy',
    title: 'UNILAB PHARMACY',
    description: 'National pharmaceutical brand outlet.',
    distance: '1.7 km',
    coords: [8.2289, 124.2469],
    category: 'Health',
    rating: 4.2,
    image: '/images/unilab.png',
  },
  {
    id: 'jebs-pharmacy',
    title: 'JEBS PHARMACY & GENERAL MERCHANDISE',
    description: 'Pharmacy and convenience items.',
    distance: '1.9 km',
    coords: [8.2262, 124.2457],
    category: 'Health',
    rating: 4.0,
    image: '/images/jebs.png',
  },

  // --- Grocery entries ---
  {
    id: 'mc-fry-store',
    title: 'MC FRY STORE',
    description: 'Local grocery store with daily essentials.',
    distance: '1.2 km',
    coords: [8.2305, 124.2440],
    category: 'Shopping',
    rating: 4.0,
    image: 'https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 'leand-enterprises',
    title: 'Leand Enterprises',
    description: 'Neighborhood grocery and provision store.',
    distance: '900 m',
    coords: [8.2279, 124.2460],
    category: 'Shopping',
    rating: 3.9,
    image: '/images/leand.png',
  },
  {
    id: 'recil-gomera-pantin',
    title: 'Recil Gomera Pantin',
    description: 'Local grocery and produce vendor.',
    distance: '1.5 km',
    coords: [8.2267, 124.2438],
    category: 'Shopping',
    rating: 3.8,
    image: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 'tres-hermanas-store',
    title: 'TRES HERMANAS STORE',
    description: 'Small grocery store with household items.',
    distance: '1.0 km',
    coords: [8.2254, 124.2473],
    category: 'Shopping',
    rating: 3.7,
    image: '/images/tres.png',
  },
  {
    id: 'mayvan-store',
    title: 'MAYVAN STORE',
    description: 'Convenience store and local grocery.',
    distance: '1.6 km',
    coords: [8.2281, 124.2444],
    category: 'Shopping',
    rating: 3.5,
    image: '/images/mayvan.png',
  },
  {
    id: 'cj-anne-vj-store',
    title: 'Cj Anne Vj Store',
    description: 'Local corner shop with groceries.',
    distance: '1.3 km',
    coords: [8.2272, 124.2466],
    category: 'Shopping',
    rating: 3.6,
    image: '/images/cj.png',
  },

  // --- Repair Services entries ---
  {
    id: 'mike-auto-repair',
    title: 'Mike Auto Repair Shop',
    description: 'Auto repair specialists with diagnostic services.',
    distance: '2.0 km',
    coords: [8.232, 124.249],
    category: 'Repair',
    rating: 5.0,
    image: '/images/mike.png',
  },
  {
    id: 'ac-tech-refrigeration',
    title: 'AC TECH Refrigeration and Air-conditioning',
    description: 'AC and refrigeration repairs and servicing.',
    distance: '2.3 km',
    coords: [8.2335, 124.2485],
    category: 'Repair',
    rating: 4.0,
    image: '/images/ac-tech-refrigeration.png',
  },
  {
    id: 'motech-iligan',
    title: 'Motech - Iligan',
    description: 'Electronics and gadget repair services.',
    distance: '1.9 km',
    coords: [8.2276, 124.2472],
    category: 'Repair',
    rating: 4.0,
    image: '/images/motech.png',
  },
  {
    id: 'lance-refrigeration',
    title: 'Lance Refrigeration & Air Conditioning Service Center',
    description: 'Refrigeration specialists for homes and businesses.',
    distance: '2.5 km',
    coords: [8.235, 124.246],
    category: 'Repair',
    rating: 3.6,
    image: '/images/lance.png',
  },
  {
    id: 'miptronics-enterprises',
    title: 'MIPTRONICS ENTERPRISES',
    description: 'General repair and electronic services.',
    distance: '2.1 km',
    coords: [8.2318, 124.2458],
    category: 'Repair',
    rating: 3.5,
    image: '/images/miptro.png',
  },

  // --- Internet Cafe entries ---
  {
    id: 'g7-internet-cafe',
    title: 'G-7 Internet Cafe',
    description: 'Internet cafe with workstations and printing.',
    distance: '1.0 km',
    coords: [8.2298, 124.2478],
    category: 'Internet',
    rating: 4.1,
    image: '/images/g7.png',
  },
  {
    id: 'gxarena-esports',
    title: 'GXArena Esports Lounge',
    description: 'Competitive gaming lounge and internet cafe.',
    distance: '1.6 km',
    coords: [8.2264, 124.2454],
    category: 'Internet',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 'power-portal-internet-cafe',
    title: 'Power Portal Internet Cafe & Printing Services',
    description: 'Internet cafe combined with printing services.',
    distance: '1.2 km',
    coords: [8.2277, 124.2441],
    category: 'Internet',
    rating: 3.7,
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 'starlink-rental-iligan',
    title: 'Starlink Rental Iligan',
    description: 'Starlink-powered internet rental and access point.',
    distance: '2.0 km',
    coords: [8.2322, 124.2462],
    category: 'Internet',
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 'kaffi-break',
    title: 'KAFFI BREAK',
    description: 'Cafe with internet access and refreshments.',
    distance: '800 m',
    coords: [8.2289, 124.2431],
    category: 'Internet',
    rating: 4.1,
    image: '/images/kaffi.png',
  },
].map((service) => ({
  likes: 0,
  ...service,
  likes: typeof service.likes === 'number' ? service.likes : 0,
  reviews: Array.isArray(service.reviews) ? service.reviews : [],
  comments: Array.isArray(service.comments) ? service.comments : []
}));

export default services;
