const services = [
  {
    id: 'laundry',
    title: 'Laundry',
    description: 'Quick and affordable local laundry services.',
    distance: '1.2 km',
    coords: [8.233, 124.247],
    category: 'Home',
    rating: 4.8,
    image: 'https://i.pinimg.com/originals/55/ea/a0/55eaa00ac768ebd7672a11499e620a04.jpg',
  },
  {
    id: 'printing',
    title: 'Printing',
    description: 'Fast document printing and copying nearby.',
    distance: '800 m',
    coords: [8.226, 124.244],
    category: 'Office',
    rating: 4.3,
    image: 'https://tse4.mm.bing.net/th/id/OIP.Vq2T4aL0BpgEgtYutG-GcAHaEO?pid=Api&P=0&h=180',
  },
  {
    id: 'boarding-house',
    title: 'Boarding House',
    description: 'Affordable boarding options close by.',
    distance: '2.1 km',
    coords: [8.221, 124.249],
    category: 'Accommodation',
    rating: 4.5,
    image: 'https://tse2.mm.bing.net/th/id/OIP.xTr8dGzW2blLTkXQSrRadgHaE8?pid=Api&P=0&h=180',
  },
  {
    id: 'food-delivery',
    title: 'Food Delivery',
    description: 'Fast food delivery from local restaurants.',
    distance: '1.5 km',
    coords: [8.234, 124.248],
    category: 'Food',
    rating: 4.2,
    image: 'https://cdn.pixabay.com/photo/2015/04/08/13/13/food-712665_1280.jpg',
  },
  {
    id: 'pharmacy',
    title: 'Pharmacy',
    description: 'Nearby pharmacy for medicines and healthcare items.',
    distance: '650 m',
    coords: [8.229, 124.248],
    category: 'Health',
    rating: 4.4,
    image: 'https://tse3.mm.bing.net/th/id/OIP.rbj_nHwRqTsmkzWWOqU3bgHaE7?pid=Api&P=0&h=180',
  },
  {
    id: 'grocery',
    title: 'Grocery',
    description: 'Local grocery store with fresh produce.',
    distance: '900 m',
    coords: [8.227, 124.246],
    category: 'Shopping',
    rating: 4.0,
    image: 'https://tse4.mm.bing.net/th/id/OIP.B6YlCtNyvXJW_OvbD5osHwHaFj?pid=Api&P=0&h=180',
  },
  {
    id: 'repair-services',
    title: 'Repair Services',
    description: 'Tool and gadget repair specialists nearby.',
    distance: '1.9 km',
    coords: [8.230, 124.243],
    category: 'Repair',
    rating: 4.6,
    image: 'https://tse3.mm.bing.net/th/id/OIP.1LgriQpbIsdw5Pg6BYI8ygHaEK?pid=Api&P=0&h=180',
  },
  {
    id: 'internet-cafe',
    title: 'Internet Café',
    description: 'Workspace and online access at affordable rates.',
    distance: '750 m',
    coords: [8.228, 124.242],
    category: 'Internet',
    rating: 4.1,
    image: 'https://tse2.mm.bing.net/th/id/OIP.xZNClaC1JNGUxH6P-FgcFAHaEK?pid=Api&P=0&h=180',
  },
];

export default services;
